EventCaveWeb/Entities/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventCaveWeb.Entities
{
    public class Category
    {
        public int Id { get; set; }

        [MaxLength(15)]
        [Required]
        public string Name { get; set; }

        [MaxLength(50)]
        [Required]
        public string Description { get; set; }

        [Required]
        public string Image { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }

    public class CategoryDto
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

EventCaveWeb/Entities/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventCaveWeb.Entities
{
    public class Event
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Images { get; set; }

        [Required]
        public string Location { get; set; }

        [Required]
        public DateTime Datetime { get; set; }

        public string Description { get; set; }

        public int Limit { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public virtual ApplicationUser Host { get; set; }

        public virtual ICollection<UserEvent> Attendees { get; set; }

        public virtual ICollection<Category> Categories { get; set; }
    }
}

EventCaveWeb/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventCaveWeb.Models
{
    public class Event
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Images { get; set; }

        [Required]
        public string Location { get; set; }

        [Required]
        public DateTime Datetime { get; set; }

        public string Description { get; set; }

        public int Limit { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public virtual ApplicationUser Host { get; set; }

        public virtual ICollection<UserEvent> Attendees { get; set; }

        public virtual ICollection<Category> Categories { get; set; }
    }
}

EventCaveWeb/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventCaveWeb.ViewModels
{
    public class CategoryViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Image { get; set; }
    }
}

EventCaveWeb/ViewModels/EventViewModels.cs
using EventCaveWeb.Entities;
using EventCaveWeb.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace EventCaveWeb.ViewModels
{
    public class CreateUpdateEventViewModel
    {
        public int Id { get; set; }

        [StringLength(15)]
        [Required]
        [Display(Name = "Title")]
        public string Name { get; set; }

        [StringLength(25)]
        public string Images { get; set; }

        [StringLength(10000)]
        public string Description { get; set; }

        [Required]
        public string Location { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime Datetime { get; set; }

        public int Limit { get; set; }

       
        public IEnumerable<Category> Categories { get; set; }

        [Display(Name = "Categories")]
        public IEnumerable<int> SelectedCategoryIds { get; set; }
    }

    public class EventDetailViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public DateTime Datetime { get; set; }
        public int Limit { get; set; }
        public bool Going { get; set; }
        public ApplicationUser Host { get; set; }
        public ImgurImage HostPicture { get; set; }
        public int AttendeeCount { get; set; }
        public int SpacesLeft { get; set; }
        public ICollection<Category> Categories { get; set; }
        public IEnumerable<ImgurImage> Images { get; set; }
    }
}

EventCaveWeb/Controllers/Api/CategoriesController.cs
using EventCaveWeb.Database;
using EventCaveWeb.Entities;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Http;

namespace EventCaveWeb.Controllers.Api
{
    [Authorize]
    public class CategoriesController : ApiController
    {
        [Route("Api/Categories")]
        [HttpGet]
        public IQueryable<CategoryDto> List()
        {
            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();
            IQueryable<CategoryDto> categories = db.Categories.Select(c =>
                new CategoryDto()
                {
                    Id = c.Id,
                    Name = c.Name,
                    Description = c.Description,
                    Image = c.Image
                });
            return categories;
        }

        [Route("Api/Categories/{id}")]
        [HttpGet]
        public IHttpActionResult Single(int id)
        {
            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();
            CategoryDto categoryDto = db.Categories.Where(c => c.Id == id).Select(c =>
                new CategoryDto()
                {
                    Id = c.Id,
                    Name = c.Name,
                    Description = c.Description,
                    Image = c.Image
                }).FirstOrDefault();
            return Ok(categoryDto);
        }

        [Route("Api/Categories")]
        [HttpPost]
        public IHttpActionResult Post([FromBody] CategoryDto categoryDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();

            Category category = new Category()
            {
                Name = categoryDto.Name,
                Description = categoryDto.Description,
                Image = categoryDto.Image
            };

            db.Categories.Add(category);
            db.SaveChanges();

            return Ok(
                new
                {
                    Status = 200,
                    Message = "Category was successfully created."
                }
            );
        }

        [Route("Api/Categories/{id}")]
        [HttpPut]
        public IHttpActionResult Put(int id, [FromBody] CategoryDto categoryDto)
        {
            Category category = null;
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            using (DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>())
            {
                category = db.Categories.Find(id);

                if (category == null)
                {
                    return BadRequest("Category not found.");
                }

                category.Name = categoryDto.Name;
                category.Description = categoryDto.Description;
                category.Image = categoryDto.Image;

                db.SaveChanges();
            }

            return Ok(
                new
                {
                    Status = 200,
                    Message = "Category was successfully updated."
                }
            );
        }

        [Route("Api/Categories/{id}")]
        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            Category category;
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            using (DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>())
            {
                category = db.Categories.Find(id);

                if (category == null)
                {
                    return BadRequest(string.Format("Category ID {0} not found.", id));
                }

                db.Categories.Remove(category);
                db.SaveChanges();
            }

            return Ok(
                new
                {
                    Status = 200,
                    Message = "Category was successfully deleted."
                }
            );
        }
    }
}

EventCaveWeb/Controllers/Api/TicketsController.cs
using EventCaveWeb.Database;
using EventCaveWeb.Entities;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Http.Cors;

namespace EventCaveWeb.Controllers.Api
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    [Authorize]
    public class TicketsController : ApiController
    {
        [Route("Api/Tickets")]
        [HttpGet]
        public IQueryable<TicketDto> List()
        {
            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();
            IQueryable<TicketDto> tickets = db.Tickets.Include("Sender").Select(t =>
                new TicketDto()
                {
                    Id = t.Id,
                    Subject = t.Subject,
                    Message = t.Message,
                    Response = t.Response,
                    Resolved = t.Resolved,
                    SubmittedAt = t.SubmittedAt,
                    SenderId = t.Sender.Id,
                    SenderUsername = t.Sender.UserName
                });
            return tickets;
        }

        [Route("Api/Tickets/{id}")]
        [HttpGet]
        public TicketDto Single(int id)
        {
            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();
            TicketDto ticketDto = db.Tickets.Include("Sender").Where(t => t.Id == id).Select(t =>
                new TicketDto
                {
                    Id = t.Id,
                    Subject = t.Subject,
                    Message = t.Message,
                    Response = t.Response,
                    Resolved = t.Resolved,
                    SubmittedAt = t.SubmittedAt,
                    SenderId = t.Sender.Id,
                    SenderUsername = t.Sender.UserName
                }).FirstOrDefault();
            return ticketDto;
        }

        [Route("Api/Tickets/{id}/Resolve")]
        [HttpPost]
        public IHttpActionResult ResolveTicket(int id, [FromBody] TicketResolveDto dto)
        {
            DatabaseContext db = HttpContext.Current.GetOwinContext().Get<DatabaseContext>();
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return BadRequest(ModelState);
            }
            ticket.Response = dto.Response;
            ticket.Resolved = true;
            db.SaveChanges();
            return Ok(
                new
                {
                    Status = 200,
                    Message = "Ticket was marked as resolved."
                }
            );
        }
    }
}

EventCaveWeb/Controllers/AuthController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using EventCaveWeb.Entities;
using EventCaveWeb.ViewModels;
using EventCaveWeb.Utils;

namespace EventCaveWeb.Controllers
{
    public class AuthController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AuthController()
        {
        }

        public AuthController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Route("SignIn")]
        [HttpGet]
        [AllowAnonymous]
        public ActionResult SignIn(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [Route("SignIn")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignIn(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await SignInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    Message.Create(Response, "Welcome back! We are glad to see you again.");
                    return RedirectToLocal(returnUrl);
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        [Route("SignUp")]
        [HttpGet]
        [AllowAnonymous]
        public ActionResult SignUp()
        {
            return View();
        }

        [Route("SignUp")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignUp(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    UserName = model.UserName,
                    Email = model.Email,
                    Picture = model.Picture,
                    RegisteredAt = DateTime.Now
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                    Message.Create(Response, "Thank you for using our platform.");
                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }
            return View(model);
        }

        [Route("SignOut")]
        [HttpGet]
        [Authorize]
        public ActionResult SignOut()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

EventCaveWeb/Controllers/CategoriesController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventCaveWeb.Database;
using EventCaveWeb.Entities;
using Microsoft.AspNet.Identity.Owin;

namespace EventCaveWeb.Controllers
{
    [RoutePrefix("Categories")]
    public class CategoriesController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            DatabaseContext db = HttpContext.GetOwinContext().Get<DatabaseContext>();
            var categories = db.Categories.ToList();
            return View(categories);
        }
    }
}

EventCaveWeb/Views/Shared/Partials/Category.cshtml
<a href="@ViewBag.Url" class="card shadow text-white">
    <img src="@String.Format("https://images.weserv.nl?url={0}&h=768&w=512&fit=cover&a=entropy", ViewBag.ImageUrl)"
         class="card-img"
         alt="category-img" />
    <div class="card-img-overlay d-flex flex-column justify-content-end">
        <h5 class="card-title font-weight-bold">@ViewBag.Title</h5>
        <p class="card-text">@ViewBag.Description</p>
    </div>
</a>

EventCaveWeb/Views/Shared/Partials/Empty.cshtml
<div class="d-flex flex-column justify-content-center align-items-center text-muted ec-empty">
    <i data-feather="@(ViewBag.EmptyIcon ?? "box")"></i>
    <h5 class="font-weight-bold">@(ViewBag.EmptyTitle ?? "So empty")</h5>
</div>

EventCaveWeb/Views/Shared/Partials/Event.cshtml
@using EventCaveWeb.Entities

<a href="@Url.Action("Detail", "Events", new { id = ViewBag.Id})" class="card shadow">
    <img class="card-img-top"
         src="@String.Format("https://images.weserv.nl?url={0}&h=768&w=768&fit=cover&a=entropy", ViewBag.ImageUrl ?? "https://cdn.pixabay.com/photo/2017/08/04/07/57/calender-2579300_960_720.jpg")"
         alt="event-image.png" />
    <div class="card-body">
        <h5 class="card-title font-weight-bold" style="overflow: hidden; text-overflow:ellipsis; white-space:nowrap">@ViewBag.Title</h5>
        <div class="mb-2">
            @foreach (Category category in ViewBag.Categories)
            {
                <div class="badge badge-primary" style="overflow: hidden; text-overflow:ellipsis; white-space:nowrap">@category.Name</div>
            }
        </div>
        <div class="card-text text-muted">
            <small class="d-block">@ViewBag.Date</small>
            @if (ViewBag.Count == 1)
            {
                <small class="d-block">@ViewBag.Count person going</small>
            }
            else
            {
                <small class="d-block">@ViewBag.Count people going</small>
            }
            <small class="d-block">@ViewBag.Address</small>
        </div>
    </div>
</a>

EventCaveWeb/Views/Shared/Partials/Footer.cshtml
<footer class="bg-dark text-white py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-left">
                © 2019 UCN Bois. All rights reserved.
            </div>
        </div>
    </div>
</footer>

EventCaveWeb/Views/Shared/Partials/Messages.cshtml
@using EventCaveWeb.Utils

@{
    if (Message.Exists(Request))
    {
        <div class="ec-toast-wrapper">
            <div class="toast ec-toast">
                <div class="toast-header">
                    <span class="mr-auto">New message</span>
                    <small>just now</small>
                    <button type="button" class="ml-2 mb-1 close float-right" data-dismiss="toast">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    @Message.Get(Request)
                </div>
            </div>
        </div>
        Message.Clear(Response);
    }
}

EventCaveWeb/Views/Shared/Partials/Navbar.cshtml
@using Microsoft.AspNet.Identity

<header class="ec-header">
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light shadow-md ec-header-nav">
        <a class="navbar-brand ec-header-nav-logo" href="@Url.Action("Index", "Home")">
            <img class="img-fluid ec-header-nav-logo-image"
                 src="~/Assets/images/logo.png"
                 alt="event-cave-logo.png" />
        </a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="@Url.Action("Search", "Events")">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="@Url.Action("Index", "Categories")">Categories</a>
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="@Url.Action("UserProfile", "Users", new { UserName = User.Identity.Name })">My profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="@Url.Action("List", "Tickets")">Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="@Url.Action("SignOut", "Auth")">Sign out</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="@Url.Action("SignIn", "Auth")">Sign in</a>
                    </li>
                }
                <li class="nav-item ml-md-1">
                    <a class="d-block d-md-none nav-link text-primary font-weight-bold"
                       href="@Url.Action("Create", "Events")">Host event</a>
                    <a class="btn btn-primary d-none d-md-inline-block text-uppercase"
                       href="@Url.Action("Create", "Events")">Host event</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

EventCaveWeb/Views/Shared/Partials/Title.cshtml
<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mb-4">
    <h3 class="mb-0 font-weight-bold">@ViewBag.Title</h3>
    @if (ViewBag.ActionTitle != null && ViewBag.ActionUrl != null)
    {
        <a class="text-muted" href="@ViewBag.ActionUrl">
            <small>@ViewBag.ActionTitle</small>
        </a>
    }
</div>